/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BibleSidecarPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// BibleView.ts
var import_obsidian = require("obsidian");
var BibleViewType = "bible-view";
var DEFAULT_SETTINGS = {
  bibleVersion: "NLT",
  copyFormat: "plain",
  copyVerseReference: false,
  verseReferenceStyle: "- ",
  verseReferenceFormat: "full",
  verseReferenceInternalLinking: false,
  bibleLanguage: "en"
};
var BibleView = class extends import_obsidian.ItemView {
  constructor(leaf) {
    super(leaf);
  }
  getViewType() {
    return BibleViewType;
  }
  getDisplayText() {
    return "Bible Sidecar";
  }
  getIcon() {
    return "book-open-text";
  }
  load() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, this.settings);
    super.load();
  }
  updateSettings(newSettings) {
    this.settings = newSettings;
    this.loadBible();
  }
  async onOpen() {
    this.loadBible();
  }
  async loadBible() {
    const books = await this.generateBibleBooks(this.settings.bibleVersion);
    this.renderBooks(books);
  }
  async generateBibleBooks(language) {
    const url = `https://bolls.life/get-books/${language}`;
    const response = await (0, import_obsidian.requestUrl)(url);
    return response.json;
  }
  async getChapterContent(version, bookid, chapter) {
    const url = `https://bolls.life/get-chapter/${version}/${bookid}/${chapter}`;
    const response = await (0, import_obsidian.requestUrl)(url);
    return response.json;
  }
  convertToSuperscript(number) {
    const superscriptMap = {
      "0": "\u2070",
      "1": "\xB9",
      "2": "\xB2",
      "3": "\xB3",
      "4": "\u2074",
      "5": "\u2075",
      "6": "\u2076",
      "7": "\u2077",
      "8": "\u2078",
      "9": "\u2079"
    };
    const digits = String(number).split("");
    const superscriptedDigits = digits.map(
      (digit) => superscriptMap[digit]
    );
    return superscriptedDigits.join("");
  }
  convertToNumber(superscriptNumber) {
    const superscriptMap = {
      "\u2070": "0",
      "\xB9": "1",
      "\xB2": "2",
      "\xB3": "3",
      "\u2074": "4",
      "\u2075": "5",
      "\u2076": "6",
      "\u2077": "7",
      "\u2078": "8",
      "\u2079": "9"
    };
    const digits = superscriptNumber.split("").map(
      (digit) => superscriptMap[digit]
    );
    return parseInt(digits.join(""), 10);
  }
  renderBooks(books) {
    const { containerEl } = this;
    containerEl.empty();
    const ChapterWrapper = containerEl.createEl("div", {
      cls: "bible-wrapper"
    });
    const chapterContainer = ChapterWrapper.createEl("div", {
      cls: "chapter-container"
    });
    chapterContainer.createEl("div", {
      cls: "chapter-content"
    });
    for (const book of books) {
      if (book.bookid === 1) {
        chapterContainer.createEl("h4", {
          text: "Old Testament",
          cls: "book-divider"
        });
      }
      if (book.bookid === 40) {
        chapterContainer.createEl("hr", { cls: "book-divider" });
        chapterContainer.createEl("h4", {
          text: "New Testament",
          cls: "book-divider"
        });
      }
      chapterContainer.createEl("button", {
        text: book.name,
        attr: { id: book.bookid }
      }).addEventListener("click", async () => {
        await this.renderChapters(book, chapterContainer, books);
      });
    }
  }
  async renderChapters(book, chapterContainer, books) {
    chapterContainer.empty();
    const header = chapterContainer.createDiv({ cls: "bible-header" });
    chapterContainer.createDiv({
      cls: "controls-container"
    });
    if (import_obsidian.Platform.isMobileApp) {
      this.backButton = header.createEl("button", {
        text: "Books",
        cls: "back-button"
      });
    } else {
      this.backButton = header.createEl("button", {
        text: "Back to books",
        cls: "back-button"
      });
    }
    this.backButton.addEventListener("click", () => {
      this.onOpen();
    });
    for (let i = 1; i <= book.chapters; i++) {
      chapterContainer.createEl("button", {
        text: i.toString(),
        cls: "chapter-button"
      }).addEventListener("click", async () => {
        const chapterContentArray = await this.getChapterContent(
          this.settings.bibleVersion,
          book.bookid,
          i
        );
        chapterContainer.empty();
        this.processChapterContent(
          chapterContentArray,
          chapterContainer,
          book,
          i,
          books
        );
      });
    }
  }
  processChapterContent(chapter, chapterContainer, book, i, books) {
    chapterContainer.createEl("h2", { text: `${book.name} ${i}` });
    const controlsContainer = chapterContainer.createDiv({
      cls: "controls-container"
    });
    if (import_obsidian.Platform.isMobileApp) {
      this.previousButton = controlsContainer.createEl("button", {
        text: "Previous",
        cls: "previous-button"
      });
    } else {
      this.previousButton = controlsContainer.createEl("button", {
        text: "Previous chapter",
        cls: "previous-button"
      });
    }
    this.previousButton.addEventListener("click", async () => {
      let newChapter = i - 1;
      if (newChapter < 1) {
        newChapter = 1;
      } else {
        const previousChapterContent = await this.getChapterContent(
          this.settings.bibleVersion,
          book.bookid,
          newChapter
        );
        chapterContainer.empty();
        this.processChapterContent(
          previousChapterContent,
          chapterContainer,
          book,
          newChapter,
          books
        );
      }
    });
    if (import_obsidian.Platform.isMobileApp) {
      this.backButton = controlsContainer.createEl("button", {
        text: "Back",
        cls: "back-button"
      });
    } else {
      this.backButton = controlsContainer.createEl("button", {
        text: "Back to books",
        cls: "back-button"
      });
    }
    this.backButton.addEventListener("click", () => {
      this.onOpen();
    });
    if (import_obsidian.Platform.isMobileApp) {
      this.nextButton = controlsContainer.createEl("button", {
        text: "Next",
        cls: "next-button"
      });
    } else {
      this.nextButton = controlsContainer.createEl("button", {
        text: "Next chapter",
        cls: "next-button"
      });
    }
    this.nextButton.addEventListener("click", async () => {
      let newChapter = i + 1;
      if (newChapter > book.chapters) {
        const newBookId = book.bookid + 1;
        const newBook = books[newBookId - 1];
        newChapter = 1;
        const nextChapterContent = await this.getChapterContent(
          this.settings.bibleVersion,
          newBookId,
          newChapter
        );
        chapterContainer.empty();
        this.processChapterContent(
          nextChapterContent,
          chapterContainer,
          newBook,
          newChapter,
          books
        );
      } else {
        const nextChapterContent = await this.getChapterContent(
          this.settings.bibleVersion,
          book.bookid,
          newChapter
        );
        chapterContainer.empty();
        this.processChapterContent(
          nextChapterContent,
          chapterContainer,
          book,
          newChapter,
          books
        );
      }
    });
    const chapterContent = chapterContainer.createEl("div", {
      cls: "chapter-content"
    });
    chapterContent.empty();
    let accumulatedVerseText = "";
    function filterVerse(verse) {
      return verse.replace(/<br\s*\/?>|<\/?i>|<\/?b>/gi, "\n");
    }
    for (const verse of chapter) {
      const formattedVerseNumber = this.convertToSuperscript(verse.verse);
      const filteredVerseText = filterVerse(verse.text);
      const formattedVerse = chapterContent.createEl("span", {
        cls: "verse"
        // other properties if needed
      });
      formattedVerse.appendChild(
        document.createTextNode(
          `${formattedVerseNumber} ${filteredVerseText}`
        )
      );
      formattedVerse.addEventListener("click", () => {
        formattedVerse.classList.toggle("active-verse");
        const verseIdentifier = `${formattedVerseNumber} ${verse.text}`;
        if (formattedVerse.classList.contains("active-verse")) {
          accumulatedVerseText += verseIdentifier + " ";
        } else {
          accumulatedVerseText = accumulatedVerseText.replace(
            verseIdentifier + " ",
            ""
          );
        }
        this.renderCopyMessage(book, i, accumulatedVerseText);
      });
      chapterContent.appendChild(formattedVerse);
    }
  }
  renderCopyMessage(book, chapter, accumulatedVerseText) {
    const regex = /[\u2070\u00B9\u00B2\u00B3\u2074-\u2079]+/g;
    const verses = accumulatedVerseText.split("\n").flatMap((verse) => {
      const matches = Array.from(verse.matchAll(regex));
      if (matches.length === 0) {
        return [{ verse: 0, text: verse.trim() }];
      }
      return matches.map((match) => {
        var _a, _b, _c;
        const verseNumber = this.convertToNumber(match[0]);
        const verseStart = ((_a = match == null ? void 0 : match.index) != null ? _a : 0) + ((_c = (_b = match == null ? void 0 : match[0]) == null ? void 0 : _b.length) != null ? _c : 0);
        const verseEnd = matches.indexOf(match) === matches.length - 1 ? verse.length : Array.from(verse.matchAll(regex))[matches.indexOf(match) + 1].index;
        const verseText = verse.substring(verseStart, verseEnd).trim();
        return {
          verse: verseNumber,
          text: verseText
        };
      });
    }).sort((a, b) => {
      var _a, _b;
      return ((_a = a == null ? void 0 : a.verse) != null ? _a : 0) - ((_b = b == null ? void 0 : b.verse) != null ? _b : 0);
    });
    for (const verse of verses) {
      let verseRangeStart = 0;
      let verseRangeEnd = 0;
      let sortedText = "";
      const internalLinkStart = this.settings.verseReferenceInternalLinking === true ? `[[${book.name}]]` : `${book.name}`;
      console.log("sortedText", sortedText);
      verses.forEach((verse2, index) => {
        if (verseRangeStart === 0) {
          verseRangeStart = verse2.verse;
        }
        if (index > 0 && verses[index - 1].verse !== verse2.verse - 1) {
          verseRangeEnd = verses[index - 1].verse;
          if (this.settings.copyVerseReference) {
            sortedText += ` 
${this.settings.copyFormat === "callout" ? "> " : ""}${this.settings.verseReferenceStyle} ${internalLinkStart} ${chapter}:${verseRangeStart === verseRangeEnd ? verseRangeStart : verseRangeStart + "-" + verseRangeEnd}  

`;
          }
          verseRangeStart = verse2.verse;
        }
        sortedText += `${this.settings.copyFormat === "callout" ? "> " : ""}${this.convertToSuperscript(
          verse2.verse.toString()
        )} ${verse2.text}`;
        if (index === verses.length - 1) {
          verseRangeEnd = verse2.verse;
          if (this.settings.copyVerseReference) {
            sortedText += ` 
${this.settings.copyFormat === "callout" ? "> " : ""}${this.settings.verseReferenceStyle} ${internalLinkStart} ${chapter}:${verseRangeStart === verseRangeEnd ? verseRangeStart : verseRangeStart + "-" + verseRangeEnd} `;
          }
        }
      });
      navigator.clipboard.writeText(sortedText.trim());
      new import_obsidian.Notice(
        `Copied ${book.name} ${chapter}:${verse.verse} to clipboard`
      );
    }
  }
};

// settings.ts
var import_obsidian2 = require("obsidian");
var BibleSidecarSettingsTab = class extends import_obsidian2.PluginSettingTab {
  // Add containerEl property
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const LANGUAGE_DEFAULT_VERSIONS2 = {
      en: "NLT",
      de: "ELB",
      fr: "NBS",
      es: "BTX3",
      pt: "ARA",
      it: "NR06",
      nl: "NLD",
      ru: "SYNOD",
      ar: "SVD",
      in: "TB"
    };
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Bible language").setDesc("Choose your preferred Bible language").addDropdown(
      (dropdown) => {
        dropdown.addOption("en", "English | English");
        dropdown.addOption("es", "Spanish | Espa\xF1ol");
        dropdown.addOption("fr", "French | Fran\xE7ais");
        dropdown.addOption("de", "German | Deutsch");
        dropdown.addOption("pt", "Portuguese | Portugu\xEAs");
        dropdown.addOption("it", "Italian | Italiano");
        dropdown.addOption("nl", "Dutch | Nederlands");
        dropdown.addOption("ar", "Arabic | \u0627\u0644\u0639\u0631\u0628\u064A\u0629");
        dropdown.addOption("ru", "Russian | \u0420\u0443\u0441\u0441\u043A\u0438\u0439");
        dropdown.addOption("in", "Indonesian | Bahasa Indonesia");
        dropdown.setValue(this.plugin.settings.bibleLanguage).onChange((value) => {
          this.plugin.settings.bibleLanguage = value;
          this.plugin.settings.bibleVersion = LANGUAGE_DEFAULT_VERSIONS2[value] || LANGUAGE_DEFAULT_VERSIONS2["en"];
          const defaultVersionDropdown = containerEl.querySelector(
            "select[data-setting='default-bible-version']"
          );
          if (defaultVersionDropdown) {
            defaultVersionDropdown.value = this.plugin.settings.bibleVersion;
          }
          this.plugin.saveSettings();
          this.display();
        });
      }
    );
    new import_obsidian2.Setting(containerEl).setName("Default bible version").setDesc("Choose your preferred Bible version").addDropdown((dropdown) => {
      if (this.plugin.settings.bibleLanguage === "en") {
        dropdown.addOption("YLT", "Young's Literal Translation (1898)");
        dropdown.addOption(
          "KJV",
          "King James Version 1769 with Apocrypha"
        );
        dropdown.addOption("NKJV", "New King James Version, 1982");
        dropdown.addOption("WEB", "World English Bible");
        dropdown.addOption("RSV", "Revised Standard Version (1952)");
        dropdown.addOption("CJB", "The Complete Jewish Bible (1998)");
        dropdown.addOption("TS2009", "The Scriptures 2009");
        dropdown.addOption(
          "LXXE",
          "English version of the Septuagint Bible, 1851"
        );
        dropdown.addOption("TLV", "Tree of Life Version");
        dropdown.addOption("LSB", "The Legacy Standard Bible");
        dropdown.addOption(
          "NASB",
          "New American Standard Bible (1995)"
        );
        dropdown.addOption(
          "ESV",
          "English Standard Version 2001, 2016"
        );
        dropdown.addOption("GNV", "Geneva Bible (1599)");
        dropdown.addOption("DRB", "Douay Rheims Bible");
        dropdown.addOption(
          "NIV2011",
          "New International Version, 2011"
        );
        dropdown.addOption("NIV", "New International Version, 1984");
        dropdown.addOption("NLT", "New Living Translation, 2015");
        dropdown.addOption(
          "NRSVCE",
          "New Revised Standard Version Catholic Edition, 1993"
        );
        dropdown.addOption("NET", "New English Translation, 2007");
        dropdown.addOption("NJB1985", "New Jerusalem Bible, 1985");
        dropdown.addOption(
          "SPE",
          "Samaritan Pentateuch in English, 2013"
        );
        dropdown.addOption(
          "LBP",
          "Aramaic Of The Peshitta: Lamsa, 1933"
        );
        dropdown.addOption("AMP", "Amplified Bible, 2015");
        dropdown.addOption("MSG", "The Message, 2002");
        dropdown.addOption("LSV", "Literal Standard Version");
        dropdown.addOption(
          "BSB",
          "The Holy Bible, Berean Standard Bible"
        );
      }
      if (this.plugin.settings.bibleLanguage === "de") {
        dropdown.addOption("MB", "Menge Bibel");
        dropdown.addOption("ELB", "Elberfelder Bibel 1871");
        dropdown.addOption("SCH", "Schlachter 1951");
        dropdown.addOption("LUT", "Lutherbibel 1912");
      }
      if (this.plugin.settings.bibleLanguage === "fr") {
        dropdown.addOption("NBS", "Nouvelle Bible Segond 2002");
      }
      if (this.plugin.settings.bibleLanguage === "es") {
        dropdown.addOption("BTX3", "Biblia Textual 3ra Edicion");
        dropdown.addOption("RV2004", "Reina-Valera 2004");
        dropdown.addOption("PDT", "Palabra de Dios para Todos");
        dropdown.addOption("NVI", "Nueva Versi\xF3n Internacional");
        dropdown.addOption("NTV", "Nueva Traducci\xF3n Viviente 2009");
        dropdown.addOption("LBLA", "La Biblia de las Am\xE9ricas 1997");
      }
      if (this.plugin.settings.bibleLanguage === "pt") {
        dropdown.addOption("ARA", "Almeida Revista e Atualizada 1993");
        dropdown.addOption("NTJud", "Novo Testamento Judaico");
        dropdown.addOption("NVIPT", "Nova Vers\xE3o Internacional");
        dropdown.addOption("OL", "O Livro");
        dropdown.addOption("NVT", "Nova Vers\xE3o Transformadora 2016");
        dropdown.addOption("KJA", "King James Atualizada");
        dropdown.addOption("VFL", "B\xEDblia Sagrada Vers\xE3o F\xE1cil de Ler");
        dropdown.addOption("NAA", "Nova Almeida Atualizada 2017");
        dropdown.addOption("CNBB", "B\xEDblia CNBB (Nova Capa) 2002");
        dropdown.addOption("NBV07", "Nova B\xEDblia Viva 2007");
        dropdown.addOption("ALM21", "B\xEDblia Almeida S\xE9culo 21");
        dropdown.addOption("ARC09", "Almeida Revista e Corrigida 2009");
      }
      if (this.plugin.settings.bibleLanguage === "it") {
        dropdown.addOption("NR06", "Nuova Riveduta 2006");
        dropdown.addOption("VULG", "Biblia Sacra Vulgatam Clementinam");
      }
      if (this.plugin.settings.bibleLanguage === "nl") {
        dropdown.addOption("NLD", "De Heilige Schrift, Canisiusvertaling 1939");
        dropdown.addOption("DSV", "Statenvertaling met Stong's 1619");
        dropdown.addOption("SVRJ", "Statenvertaling Jongbloed-editie 1995");
        dropdown.addOption("HSV17", "Herziene Statenvertaling 2017");
      }
      if (this.plugin.settings.bibleLanguage === "ru") {
        dropdown.addOption("JNT", "\u0418\u0443\u0434\u0435\u0439\u0441\u043A\u0430\u044F \u041D\u043E\u0432\u044B\u0439 \u0417\u0430\u0432\u0435\u0442");
        dropdown.addOption("NRT", "\u041D\u043E\u0432\u044B\u0439 \u0420\u0443\u0441\u0441\u043A\u0438\u0439 \u041F\u0435\u0440\u0435\u0432\u043E\u0434");
        dropdown.addOption("SYNOD", "\u0421\u0438\u043D\u043E\u0434\u0430\u043B\u044C\u043D\u044B\u0439 \u043F\u0435\u0440\u0435\u0432\u043E\u0434");
        dropdown.addOption("TNHR", "\u041D\u0435\u0432\u0438\u0438\u043C \u0438 \u041A\u0442\u0443\u0432\u0438\u043C");
        dropdown.addOption("RBS2", "\u0420\u0443\u0441\u0441\u043A\u0438\u0439 \u0421\u0438\u043D\u043E\u0434\u0430\u043B\u044C\u043D\u044B\u0439 \u043F\u0435\u0440\u0435\u0432\u043E\u0434 2015");
        dropdown.addOption("BTI", "\u0411\u0438\u0431\u043B\u0438\u044F \u0422\u0438\u0445\u043E\u0433\u043E \u041E\u043A\u0435\u0430\u043D\u0430 2015");
      }
      if (this.plugin.settings.bibleLanguage === "ar") {
        dropdown.addOption("SVD", "Smith & Van Dyke");
      }
      if (this.plugin.settings.bibleLanguage === "in") {
        dropdown.addOption("TB", "Terjemahan Baru");
      }
      dropdown.setValue(this.plugin.settings.bibleVersion).onChange((value) => {
        this.plugin.settings.bibleVersion = value;
        this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Copy format").setHeading().setDesc("Choose how you want the Bible text to be copied").addDropdown((dropdown) => {
      dropdown.addOption("plain", "Plain text");
      dropdown.addOption("callout", "Callout");
      dropdown.setValue(this.plugin.settings.copyFormat).onChange((value) => {
        this.plugin.settings.copyFormat = value;
        this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Reference format").setHeading().setDesc("Include the verse reference when copying (recommended)").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.copyVerseReference).onChange((value) => {
        this.plugin.settings.copyVerseReference = value;
        this.plugin.saveSettings();
        verseReferenceListSetting.settingEl.style.display = value ? "block" : "none";
        verseReferenceFormatSetting.settingEl.style.display = value ? "block" : "none";
        verseReferenceInternalLinkingSetting.settingEl.style.display = value ? "block" : "none";
        this.display();
      });
    });
    const verseReferenceListSetting = new import_obsidian2.Setting(containerEl).setName("Verse reference format").setDesc("Choose the style of the verse reference").addDropdown((dropdown) => {
      dropdown.addOption("- ", "List (-)");
      dropdown.addOption(">", "Callout (>)");
      dropdown.addOption("-- ", "Double Dash (--)");
      dropdown.addOption("~", "Tilde (~)");
      dropdown.setValue(this.plugin.settings.verseReferenceStyle).onChange((value) => {
        this.plugin.settings.verseReferenceStyle = value;
        this.plugin.saveSettings();
      });
    });
    const verseReferenceFormatSetting = new import_obsidian2.Setting(containerEl).setName("Verse reference format").setDesc("Choose the format of the verse reference").addDropdown(
      (dropdown) => {
        dropdown.addOption("full", "Full (e.g. John 3:16)");
        dropdown.addOption("short", "Short (e.g. 1:1)");
        dropdown.setValue(this.plugin.settings.verseReferenceFormat).onChange((value) => {
          this.plugin.settings.verseReferenceFormat = value;
          this.plugin.saveSettings();
        });
      }
    );
    const verseReferenceInternalLinkingSetting = new import_obsidian2.Setting(containerEl).setName("Enable internal linking eg. [[John]]").setDesc("Choose the format of the verse reference").addToggle(
      (toggle) => {
        toggle.setValue(this.plugin.settings.verseReferenceInternalLinking).onChange((value) => {
          this.plugin.settings.verseReferenceInternalLinking = value;
          this.plugin.saveSettings();
          this.display();
        });
      }
    );
    if (!this.plugin.settings.copyVerseReference) {
      verseReferenceListSetting.settingEl.style.display = "none";
      verseReferenceFormatSetting.settingEl.style.display = "none";
      verseReferenceInternalLinkingSetting.settingEl.style.display = "none";
    }
  }
};

// main.ts
var DEFAULT_SETTINGS2 = {
  bibleVersion: "NLT",
  copyFormat: "plain",
  copyVerseReference: false,
  verseReferenceStyle: "- ",
  verseReferenceFormat: "full",
  verseReferenceInternalLinking: false,
  verseReferenceInternalLinkingFormat: "short",
  bibleLanguage: "en"
};
var LANGUAGE_DEFAULT_VERSIONS = {
  en: "NLT",
  de: "ELB",
  fr: "NBS",
  es: "BTX3",
  pt: "ARA",
  it: "NR06",
  nl: "NLD",
  ru: "SYNOD",
  ar: "SVD",
  in: "TB"
};
var BibleSidecarPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.toggleBibleSidecarView = async () => {
      const existing = this.app.workspace.getLeavesOfType(BibleViewType);
      if (existing.length) {
        this.app.workspace.revealLeaf(existing[0]);
        return;
      }
      const rightLeaf = this.app.workspace.getRightLeaf(false);
      if (rightLeaf) {
        await rightLeaf.setViewState({
          type: BibleViewType,
          active: true
        });
      }
      this.app.workspace.revealLeaf(
        this.app.workspace.getLeavesOfType(BibleViewType)[0]
      );
    };
    this.updateBibleViewSettings = (newSettings) => {
      if (this.view) {
        this.view.updateSettings(newSettings);
      }
    };
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new BibleSidecarSettingsTab(this.app, this));
    this.registerView(
      BibleViewType,
      (leaf) => {
        const view = new BibleView(leaf);
        this.view = view;
        view.settings = this.settings;
        return view;
      }
    );
    this.addRibbonIcon(
      "book-open-text",
      "Bible Sidecar",
      (evt) => {
        this.toggleBibleSidecarView();
      }
    );
    this.addCommand({
      id: "open-bible-sidecar",
      name: "Open Bible Sidecar",
      callback: this.toggleBibleSidecarView,
      icon: "book-open-text"
    });
    this.initLeaf();
  }
  initLeaf() {
    if (this.app.workspace.getLeavesOfType(BibleViewType).length) {
      console.log("Bible view already open");
      return;
    }
  }
  async loadSettings() {
    await this.loadData().then((data) => {
      this.settings = Object.assign(
        {},
        DEFAULT_SETTINGS2,
        data,
        {
          bibleVersion: (data == null ? void 0 : data.bibleLanguage) && LANGUAGE_DEFAULT_VERSIONS[data.bibleLanguage] ? LANGUAGE_DEFAULT_VERSIONS[data.bibleLanguage] : LANGUAGE_DEFAULT_VERSIONS["en"]
          // Default to "en" if not found
        }
      );
    });
  }
  async saveSettings() {
    await this.saveData(this.settings);
    console.log("Saved settings", this.settings);
    this.updateBibleViewSettings(this.settings);
  }
};

/* nosourcemap */