#!/usr/bin/env python3
"""Format vault-export diagnostics without writing datasets or notes."""

from __future__ import annotations

import re
from urllib.parse import unquote

UNRESOLVED_KIND_ORDER = ("scripture", "topical")
UNRESOLVED_KIND_HEADINGS = {"scripture": "Scripture", "topical": "Topical"}
# Canonical book names and abbreviations; the regex sorts longest first.
BIBLE_BOOK_NAMES = (
    "Song of Solomon",
    "Song of Songs",
    "1 Chronicles",
    "2 Chronicles",
    "1 Corinthians",
    "2 Corinthians",
    "1 Thessalonians",
    "2 Thessalonians",
    "1 Timothy",
    "2 Timothy",
    "1 Samuel",
    "2 Samuel",
    "1 Kings",
    "2 Kings",
    "1 Peter",
    "2 Peter",
    "1 John",
    "2 John",
    "3 John",
    "1 Chron",
    "2 Chron",
    "1 Thess",
    "2 Thess",
    "Deuteronomy",
    "Ecclesiastes",
    "Lamentations",
    "Philippians",
    "Revelation",
    "Zechariah",
    "Zephaniah",
    "Habakkuk",
    "Leviticus",
    "Nehemiah",
    "Obadiah",
    "Galatians",
    "Ephesians",
    "Colossians",
    "Philemon",
    "Hebrews",
    "Matthew",
    "Genesis",
    "Exodus",
    "Numbers",
    "Joshua",
    "Judges",
    "Esther",
    "Psalms",
    "Psalm",
    "Proverbs",
    "Isaiah",
    "Jeremiah",
    "Ezekiel",
    "Daniel",
    "Hosea",
    "Amos",
    "Jonah",
    "Micah",
    "Nahum",
    "Haggai",
    "Malachi",
    "Romans",
    "James",
    "Jude",
    "Mark",
    "Luke",
    "John",
    "Acts",
    "Titus",
    "Ruth",
    "Ezra",
    "Joel",
    "Job",
    "1 Chr",
    "2 Chr",
    "1 Cor",
    "2 Cor",
    "1 Sam",
    "2 Sam",
    "1 Kgs",
    "2 Kgs",
    "1 Pet",
    "2 Pet",
    "1 Tim",
    "2 Tim",
    "1 Th",
    "2 Th",
    "1 Co",
    "2 Co",
    "1 Sa",
    "2 Sa",
    "1 Ki",
    "2 Ki",
    "1 Pe",
    "2 Pe",
    "1 Ti",
    "2 Ti",
    "1 Jn",
    "2 Jn",
    "3 Jn",
    "Exod",
    "Deut",
    "Josh",
    "Judg",
    "Esth",
    "Eccl",
    "Cant",
    "Ezek",
    "Obad",
    "Zeph",
    "Zech",
    "Matt",
    "Rom",
    "Gal",
    "Eph",
    "Phil",
    "Col",
    "Phlm",
    "Heb",
    "Jas",
    "Rev",
    "Gen",
    "Exo",
    "Lev",
    "Num",
    "Deu",
    "Jdg",
    "Neh",
    "Psa",
    "Prov",
    "Ecc",
    "Song",
    "Isa",
    "Jer",
    "Lam",
    "Eze",
    "Dan",
    "Hos",
    "Mic",
    "Nah",
    "Hab",
    "Hag",
    "Zec",
    "Mal",
    "Mat",
    "Luk",
    "Php",
    "Tit",
    "Phm",
    "Pet",
    "Cor",
    "Tim",
    "Jn",
    "Mt",
    "Mk",
    "Lk",
    "Ps",
)

SCRIPTURE_REFERENCE_RE = re.compile(
    r"^(?:"
    + "|".join(
        re.escape(name)
        for name in sorted(BIBLE_BOOK_NAMES, key=len, reverse=True)
    )
    + r")\s+\d+(?:-\d+|(?:[_:.]\d+(?:-\d+)?))?$",
    re.IGNORECASE,
)

def unresolved_reference_kind(reference: str) -> str:
    """Classify an unresolved target as a scripture stub or a topical stub."""
    text = unquote(reference).strip().replace("\\", "/").removeprefix("./")
    if text.lower().endswith(".md"):
        text = text[:-3]
    leaf = re.sub(r"\s+", " ", text.rsplit("/", 1)[-1].strip())
    if SCRIPTURE_REFERENCE_RE.fullmatch(leaf):
        return "scripture"
    return "topical"


def format_occurrence_lines(source_lines: list[int]) -> str:
    """Render diagnostic source lines as `line N` or `lines N, M`."""
    if len(source_lines) == 1:
        return f"line {source_lines[0]}"
    return "lines " + ", ".join(str(line) for line in source_lines)


def format_unresolved_link_checklist(data: dict) -> str:
    """Return a deterministic owner checklist grouped by kind and source note."""
    unresolved = [
        diagnostic
        for diagnostic in data["linkDiagnostics"]["unresolved"]
        if not str(diagnostic.get("reason", "")).startswith("excluded from export")
    ]
    ambiguous_count = len(data["linkDiagnostics"]["ambiguous"])
    lines = [
        "# Unresolved link checklist",
        "",
        "Generated by tools/generate_vault_data.py. Do not hand-edit.",
        "",
        (
            f"{len(unresolved)} unresolved note links remain as "
            "scripture or topical stubs, not path typos."
        ),
        f"{ambiguous_count} ambiguous note links.",
    ]
    if not unresolved:
        return "\n".join(lines + ["", "No unresolved scripture or topical stubs.", ""])

    grouped: dict[str, dict[str, list[dict]]] = {
        kind: {} for kind in UNRESOLVED_KIND_ORDER
    }
    for diagnostic in unresolved:
        kind = unresolved_reference_kind(diagnostic["reference"])
        grouped[kind].setdefault(diagnostic["source"], []).append(diagnostic)

    for kind in UNRESOLVED_KIND_ORDER:
        by_source = grouped[kind]
        count = sum(len(entries) for entries in by_source.values())
        if count == 0:
            continue
        lines.extend(["", f"## {UNRESOLVED_KIND_HEADINGS[kind]} ({count})"])
        for source in sorted(by_source, key=str.casefold):
            lines.extend(["", f"### {source}", ""])
            entries = sorted(
                by_source[source],
                key=lambda item: (
                    item["lines"][0],
                    item["type"].casefold(),
                    item["reference"].casefold(),
                ),
            )
            for diagnostic in entries:
                location = format_occurrence_lines(diagnostic["lines"])
                reason = diagnostic.get("reason")
                reason_suffix = f" [{reason}]" if reason else ""
                lines.append(
                    f"- [ ] {diagnostic['type']} `{diagnostic['reference']}` "
                    f"({location}){reason_suffix}"
                )
    lines.append("")
    return "\n".join(lines)


def format_dataset_summary(data: dict) -> str:
    """One-screen vault snapshot for --check / --report-links (no note edits)."""
    counts = data.get("counts") or {}
    diagnostics = data.get("linkDiagnostics") or {}
    unresolved = diagnostics.get("unresolved") or []
    ambiguous = diagnostics.get("ambiguous") or []
    folders = data.get("folders") or []
    return "\n".join(
        [
            (
                f"Vault snapshot: {counts.get('notes', 0)} notes, "
                f"{counts.get('canvas', 0)} canvas, {counts.get('links', 0)} links, "
                f"{len(folders)} folders."
            ),
            (
                f"Link health: {len(unresolved)} unresolved, "
                f"{len(ambiguous)} ambiguous."
            ),
        ]
    )


def format_link_diagnostics(data: dict) -> str:
    """Return unresolved and ambiguous note links grouped for human triage."""
    diagnostics = data["linkDiagnostics"]
    unresolved = diagnostics["unresolved"]
    ambiguous = diagnostics["ambiguous"]
    lines = [
        f"Link diagnostics: {len(unresolved)} unresolved, {len(ambiguous)} ambiguous"
    ]
    if not unresolved and not ambiguous:
        return "\n".join(lines + ["", "No unresolved or ambiguous note links."])

    by_source: dict[str, list[tuple[str, dict]]] = {}
    for kind, entries in (("unresolved", unresolved), ("ambiguous", ambiguous)):
        for diagnostic in entries:
            by_source.setdefault(diagnostic["source"], []).append((kind, diagnostic))

    for source in sorted(by_source, key=str.casefold):
        lines.extend(("", source))
        entries = sorted(
            by_source[source],
            key=lambda item: (
                item[1]["lines"][0],
                item[0] != "unresolved",
                item[1]["type"].casefold(),
                item[1]["reference"].casefold(),
            ),
        )
        for kind, diagnostic in entries:
            location = format_occurrence_lines(diagnostic["lines"])
            label = "excluded" if diagnostic.get("reason") else kind
            lines.append(
                f"  - {label} {diagnostic['type']} ({location}): "
                f"{diagnostic['reference']}"
            )
            reason = diagnostic.get("reason")
            if reason:
                lines.append(f"    reason: {reason}")
            candidates = diagnostic.get("candidates", [])
            if candidates:
                lines.append("    candidates: " + ", ".join(candidates))
    return "\n".join(lines)


# Export exclusion omits draft notes from the generated dataset only.
# Export exclusion does not make files private in a public Git repository.
EXPORT_EXCLUSION_PRIVACY_NOTICE = (
    "Export exclusion does not make files private in a public Git repository."
)
PREVIEW_WRITES_NOTHING = (
    "Preview only: neither this repo's pages/vault-data.json nor the portfolio "
    "copy was written."
)


def format_exclusion_preview(
    excluded: list[tuple[str, str]],
    unmatched: list[str],
) -> str:
    """List draft notes the export policy would omit. Does not write."""
    lines = [
        "Export exclusion preview",
        "Policy: YAML frontmatter draft: true, or an exact vault-relative path "
        "in tools/export-exclusions.txt.",
        EXPORT_EXCLUSION_PRIVACY_NOTICE,
        f"Excluded notes ({len(excluded)}):",
    ]
    if excluded:
        for path, reason in excluded:
            lines.append(f"- {path} ({reason})")
    else:
        lines.append("- none")
    lines.append(f"Unmatched policy paths ({len(unmatched)}):")
    if unmatched:
        for path in unmatched:
            lines.append(f"- {path}")
    else:
        lines.append("- none")
    return "\n".join(lines)


def _section(title: str, rows: list[str]) -> list[str]:
    body = rows if rows else ["- none"]
    return [f"{title} ({len(rows)}):", *body]


def format_export_changes(before: dict, after: dict) -> str:
    """Semantic before/after export report. The caller must not write datasets."""

    def nodes_of(data: dict, node_type: str) -> dict[str, dict]:
        return {
            node["id"]: node
            for node in data.get("nodes") or []
            if node.get("type") == node_type and node.get("id")
        }

    def author_edges(data: dict) -> set[tuple[str, str, str]]:
        edges = set()
        for link in data.get("links") or []:
            if link.get("type") in {"wikilink", "markdown", "canvas"}:
                edges.add((link["source"], link["target"], link["type"]))
        return edges

    before_notes = nodes_of(before, "note")
    after_notes = nodes_of(after, "note")
    added = sorted(set(after_notes) - set(before_notes), key=str.casefold)
    removed = sorted(set(before_notes) - set(after_notes), key=str.casefold)
    changed = sorted(
        (
            note_id
            for note_id in set(before_notes) & set(after_notes)
            if before_notes[note_id].get("content") != after_notes[note_id].get("content")
        ),
        key=str.casefold,
    )
    resolved_edges = author_edges(after) - author_edges(before)
    broken_edges = author_edges(before) - author_edges(after)

    def edge_row(edge: tuple[str, str, str]) -> str:
        source, target, link_type = edge
        return f"- {source} -> {target} ({link_type})"

    def edge_sort(edge: tuple[str, str, str]) -> tuple[str, str, str]:
        return tuple(part.casefold() for part in edge)

    before_canvas = nodes_of(before, "canvas")
    after_canvas = nodes_of(after, "canvas")
    canvas_rows = [
        f"- added: {canvas_id}"
        for canvas_id in sorted(set(after_canvas) - set(before_canvas), key=str.casefold)
    ]
    canvas_rows.extend(
        f"- removed: {canvas_id}"
        for canvas_id in sorted(set(before_canvas) - set(after_canvas), key=str.casefold)
    )
    canvas_rows.extend(
        f"- content: {canvas_id}"
        for canvas_id in sorted(
            (
                canvas_id
                for canvas_id in set(before_canvas) & set(after_canvas)
                if before_canvas[canvas_id].get("content")
                != after_canvas[canvas_id].get("content")
            ),
            key=str.casefold,
        )
    )
    lines = [
        "Export preview",
        PREVIEW_WRITES_NOTHING,
        *_section("Added notes", [f"- {note_id}" for note_id in added]),
        *_section("Removed notes", [f"- {note_id}" for note_id in removed]),
        *_section("Changed bodies", [f"- {note_id}" for note_id in changed]),
        *_section(
            "Resolved links",
            [edge_row(edge) for edge in sorted(resolved_edges, key=edge_sort)],
        ),
        *_section(
            "Broken links",
            [edge_row(edge) for edge in sorted(broken_edges, key=edge_sort)],
        ),
        *_section("Canvas changes", canvas_rows),
    ]
    return "\n".join(lines)


def format_rename_preview(report: dict) -> str:
    """Render a read-only note-move preview, including ambiguous destinations."""
    lines = ["Rename preview", f"Source: {report['source_status']}"]
    if report["source_status"] == "resolved":
        lines.append(f"Note: {report['source_path']}")
        if report.get("source_exclusion"):
            lines.append(f"Export status: {report['source_exclusion']}")
    elif report["source_status"] == "missing":
        lines.append(f"No note matches `{report['source_spec']}`.")
    else:
        lines.append("No source note was selected.")
        candidates = ", ".join(report.get("source_candidates") or [])
        lines.append(f"Candidates: {candidates}")

    destination_status = report["destination_status"]
    if destination_status == "new":
        lines.append(f"Destination: new path {report['destination_label']}")
    elif destination_status == "existing":
        lines.append(f"Destination: existing note {report['destination_label']}")
    elif destination_status == "unchanged":
        lines.append(f"Destination: unchanged {report['destination_label']}")
    elif destination_status == "outside":
        lines.append("Destination: outside vault")
        lines.append("The destination leaves the vault and was not used.")
    else:
        lines.append("Destination: ambiguous")
        lines.append("No destination was selected.")
        if report.get("destination_detail"):
            lines.append(report["destination_detail"])
        candidates = ", ".join(report.get("destination_candidates") or [])
        lines.append(f"Candidates: {candidates}")

    if not report.get("incoming_collected"):
        lines.append(
            "Incoming references were not collected because the source note is "
            "not a single note."
        )
        return "\n".join(lines)

    incoming = report["incoming"]
    for label, key in (
        ("Incoming wikilinks", "wikilink"),
        ("Incoming markdown links", "markdown"),
        ("Incoming canvas references", "canvas"),
        ("Ambiguous incoming references", "ambiguous"),
    ):
        rows = incoming.get(key) or []
        lines.append(f"{label} ({len(rows)}):")
        if not rows:
            lines.append("- none")
            continue
        for item in rows:
            lines.append(f"- {item}")
    return "\n".join(lines)
